# Generated by Django 2.1.7 on 2019-03-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customeraccounts_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccounts',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customeraccounts',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='CustomerAccounts',
        ),
    ]
