# Generated by Django 2.1.7 on 2019-03-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20190330_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='superuser',
        ),
    ]
