# Generated by Django 2.1.7 on 2019-03-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0001_initial'),
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('isCredit', models.BooleanField(default=False)),
                ('isCancel', models.BooleanField(default=False)),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Invoices', to='Branch.Branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Invoices', to='Supplier.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('isCancel', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='Restock.SupplierInvoice')),
            ],
        ),
    ]
