# Generated by Django 2.1.7 on 2019-03-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieraccount',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='SupplierAccount',
        ),
    ]
