# Generated by Django 2.1.7 on 2019-03-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNo', models.CharField(max_length=20)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('isCredit', models.BooleanField(default=False)),
                ('deliveryType', models.IntegerField()),
                ('isCancel', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isCancel', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='Sales.CustomerInvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.StockBranchSupplierItem')),
            ],
        ),
    ]
