# Generated by Django 2.1.7 on 2019-03-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20190330_1640'),
        ('Sales', '0002_remove_customerinvoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraccounts',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.CustomerInvoice'),
        ),
    ]
