# Generated by Django 2.1.7 on 2019-03-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSupplierItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('isDelete', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockBranchSupplierItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
                ('branchSupplierItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.BranchSupplierItem')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='branchsupplieritem',
            name='supplierItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.SupplierItem'),
        ),
    ]
